// Code generated by coz. DO NOT EDIT.
/**
 * 
 * @module modeling
 */
'use strict'

const metaModel_ = require('./metaModel')
const resourceModel_ = require('./resourceModel')

// `module.exports` overrides these `exports.*`, but still needs them for lebab (https://github.com/lebab/lebab)
exports.metaModel = metaModel_
exports.resourceModel = resourceModel_

module.exports = {
  metaModel: metaModel_,
  resourceModel: resourceModel_,
}
