// Code generated by coz. DO NOT EDIT.
/**
 * 
 * @module dump functions
 */
'use strict'

const mysqlDump_ = require('./mysqlDump')

// `module.exports` overrides these `exports.*`, but still needs them for lebab (https://github.com/lebab/lebab)
exports.mysqlDump = mysqlDump_

module.exports = {
  mysqlDump: mysqlDump_,
}
