// Code generated by coz. DO NOT EDIT.
/**
 * Relational database driver for the-db
 * @module the-driver-rdb
 */
'use strict'

const TheDriverRDB_ = require('./TheDriverRDB')
const create_ = require('./create')
const helpers_ = require('./helpers')
const mixins_ = require('./mixins')
const modeling_ = require('./modeling')
const parsing_ = require('./parsing')
const default__ = require('./default')

// `module.exports` overrides these `exports.*`, but still needs them for lebab (https://github.com/lebab/lebab)
exports.TheDriverRDB = TheDriverRDB_
exports.create = create_
exports.helpers = helpers_
exports.mixins = mixins_
exports.modeling = modeling_
exports.parsing = parsing_

module.exports = default__
