// Code generated by coz. DO NOT EDIT.
/**
 * 
 * @module parsing
 */
'use strict'

const parseAttributeName_ = require('./parseAttributeName')
const parseFilter_ = require('./parseFilter')
const parseInboundAttributes_ = require('./parseInboundAttributes')
const parseOutboundAttributes_ = require('./parseOutboundAttributes')
const parseSort_ = require('./parseSort')

// `module.exports` overrides these `exports.*`, but still needs them for lebab (https://github.com/lebab/lebab)
exports.parseAttributeName = parseAttributeName_
exports.parseFilter = parseFilter_
exports.parseInboundAttributes = parseInboundAttributes_
exports.parseOutboundAttributes = parseOutboundAttributes_
exports.parseSort = parseSort_

module.exports = {
  parseAttributeName: parseAttributeName_,
  parseFilter: parseFilter_,
  parseInboundAttributes: parseInboundAttributes_,
  parseOutboundAttributes: parseOutboundAttributes_,
  parseSort: parseSort_,
}
