// Code generated by coz. DO NOT EDIT.
/**
 * 
 * @module parsing
 */
'use strict'

const parseOutboundAttributes_ = require('./parseOutboundAttributes')

// `module.exports` overrides these `exports.*`, but still needs them for lebab (https://github.com/lebab/lebab)
exports.parseOutboundAttributes = parseOutboundAttributes_

module.exports = {
  parseOutboundAttributes: parseOutboundAttributes_,
}
